# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherRobot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherRobot
pod 'AlamofireObjectMapper', '~> 5.0'

  target 'WeatherRobotTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeatherRobotUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
